---

- name: Install Zabbix, PostgreSQL
  hosts: all
  become: yes

  vars:
    apache_vhost: ./config/zabbix.conf
    zabbix_conf: ./config/zabbix_server.conf
    zabbix_proxy_conf: ./config/zabbix_proxy.conf
    zabbix_gui_conf: ./config/zabbix.conf.php

  tasks:
  
  - name: Adding repo
    shell: "wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb && dpkg -i zabbix-release_5.0-1+bionic_all.deb && apt update"    
   
  - name: Install Services on Debian like OS
    apt: "name={{ item }} state=latest install_recommends=yes"
    loop:
      - postgresql
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php7.2-pgsql
      - zabbix-apache-conf
      - zabbix-agent
      - python-pip
      - zabbix-proxy-pgsql
  
  - name: Install psycopg2
    shell: "pip install psycopg2"

  - name: Copying apache config
    copy: src={{ apache_vhost }} dest=/etc/apache2/sites-available/
  
  - name: Simlink to apache2
    file:
      src: /etc/apache2/sites-available/zabbix.conf
      dest: /etc/apache2/sites-enabled/zabbix.conf
      state: link
      force: true
    notify: Restart Apache2 

  - name: Configuring Zabbix-gui
    copy: src={{ zabbix_gui_conf }} dest=/usr/share/zabbix/conf/

  - name: Configuring Zabbix-server
    copy: src={{ zabbix_conf }} dest=/etc/zabbix/
    notify: Restart Zabbix-server
  
  - name: Configuring Zabbix-proxy
    copy: src={{ zabbix_proxy_conf }} dest=/etc/zabbix/
    notify: Restart Zabbix-proxy
 
  - name: Adding zabbix user to PostgreSQL
    become_user: postgres
    postgresql_user:
       name: zabbix
       password: otoo=H3A
       encrypted: yes

  - name: Unpack sql dump   # This was neded for "Load dump to zabbix database" action
    shell: "gzip -kfd /usr/share/doc/zabbix-server-pgsql/create.sql.gz && gzip -kfd /usr/share/doc/zabbix-proxy-pgsql/schema.sql.gz"

  - name: Create zabbix DB
    become_user: postgres
    postgresql_db:
       name: "{{ item }}"
       owner: zabbix
    loop:
      - zabbix
      - zabbix_proxy  

  - name: Load dump to zabbix database  
    postgresql_db: 
       name: zabbix
       login_host: 127.0.0.1
       login_user: zabbix
       login_password: otoo=H3A
       state: restore
       target: /usr/share/doc/zabbix-server-pgsql/create.sql  

  - name: Load dump to zabbix-proxy database
    postgresql_db:
       name: zabbix_proxy
       login_host: 127.0.0.1
       login_user: zabbix
       login_password: otoo=H3A
       state: restore
       target: /usr/share/doc/zabbix-proxy-pgsql/schema.sql       
 

  handlers:

  - name: Restart Apache2
    service: 
      name: apache2 
      state: restarted 
      enabled: yes

  - name: Restart Zabbix-server
    service: 
      name: zabbix-server 
      state: restarted
      enabled: yes

  - name: Restart Zabbix-proxy
    service: 
      name: zabbix-proxy
      state: restarted
      enabled: yes

  - name: Install psycopg2
    shell: "pip install psycopg2"  
