---

- name: Install Zabbix, PostgreSQL
  hosts: all
  become: yes

  tasks:

  - name: Install Zabbix server + Proxy + UI + PostgreSQL
    apt: "name=zabbix-server-pgsql,apache2 state=latest install_recommends=yes"


  - name: Start and enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - apache2
      - zabbix-server
      - postgresql 

