---

- name: Install Zabbix, PostgreSQL
  hosts: all
  become: yes

  vars:
    apache_vhost: ./config/zabbix.conf
    zabbix_conf: ./config/zabbix_server.conf

  tasks:
  - name: Check OS family
    debug: os_family=ansible_os_family

  - block: # =======Commands for RedHat based systems=======

  - name: Adding repo RPM
    shell: "rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm && dnf claen all"

  - name: Install Services on Redhat like OS
    yum: "name={{ item }} state=latest install_recommends=yes "
    loop:
      - postgresql
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php7.2-pgsql
      - zabbix-apache-conf
      - zabbix-agent
      - python-pip
      - zabbix-proxy-pgsql
    notify: Install psycopg2   
 
  - name: Copying httpd config
    copy: src={{ apache_vhost }} dest=/etc/httpd/sites-available/

  - name: Simlink to vhost httpd
    file:
      src: /etc/httpd/sites-available/zabbix.conf
      dest: /etc/httpd/sites-enabled/zabbix.conf
      state: link
      force: true
    notify: Restart Apache2
    
    when: ansible_os_family ==  "CentOS"

  - block: # =======Commands for Debian based systems=======  

  - name: Adding repo
    shell: "wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb && dpkg -i zabbix-release_5.0-1+bionic_all.deb && apt update"    
   
  - name: Install Services on Debian like OS
    apt: "name={{ item }} state=latest install_recommends=yes "
    #name=zabbix-server-pgsql,zabbix-frontend-php,php7.2-pgsql,zabbix-apache-conf,zabbix-agent,python-pip,postgresql,zabbix-proxy state=latest install_recommends=yes
    loop:
      - postgresql
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php7.2-pgsql
      - zabbix-apache-conf
      - zabbix-agent
      - python-pip
      - zabbix-proxy-pgsql
  
  - name: Install psycopg2
    shell: "pip install psycopg2"

  - name: Copying apache config
    copy: src={{ apache_vhost }} dest=/etc/apache2/sites-available/
  
  - name: Simlink to apache2
    file:
      src: /etc/apache2/sites-available/zabbix.conf
      dest: /etc/apache2/sites-enabled/zabbix.conf
      state: link
      force: true
    notify: Restart Apache2  

    when: ansible_os_family ==  "Ubuntu"


#- name: Install psycopg2  
#shell: "pip install psycopg2"

  - name: Configuring Zabbix-server
    copy: src={{ zabbix_conf }} dest=/etc/zabbix/
    notify: Restart Zabbix-server

  - name: Adding zabbix user to PostgreSQL
    #become: true
    become_user: postgres
    postgresql_user:
       name: zabbix
       password: otoo=H3A
       encrypted: yes

  - name: Unpack sql dump   # This was neded for "Load dump to zabbix database" action
    shell: "gzip -kfd /usr/share/doc/zabbix-server-pgsql/create.sql.gz && gzip -kfd /usr/share/doc/zabbix-proxy-pgsql/schema.sql.gz"

  - name: Create zabbix DB
    become_user: postgres
    postgresql_db:
       name: "{{ item }}"
       owner: zabbix
    loop:
      - zabbix
      - zabbix_proxy  

  - name: Load dump to zabbix database  
    # shell: "zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix"
    postgresql_db: # It's not importing anything to db, idk why? https://docs.ansible.com/ansible/2.8/modules/postgresql_db_module.html#postgresql-db-module
       name: zabbix
       login_host: 127.0.0.1
       login_user: zabbix
       login_password: otoo=H3A
       state: restore
       target: /usr/share/doc/zabbix-server-pgsql/create.sql  

  - name: Load dump to zabbix-proxy database
    postgresql_db:
       name: zabbix_proxy
       login_host: 127.0.0.1
       login_user: zabbix
       login_password: otoo=H3A
       state: restore
       target: /usr/share/doc/zabbix-proxy-pgsql/schema.sql       
  
  handlers:

  - name: Restart Apache2
    service: name=apache2 state=restarted 

  - name: Restart Zabbix-server
    service: name=zabbix-server state=restarted 

  - name: Restart Zabbix-proxy
    service: name=zabbix-proxy state=restarted 

  - name: Install psycopg2
    shell: "pip install psycopg2"  
